app/models/task.py
from datetime import datetime
from flask import url_for, Markup
from app import db
from decimal import Decimal
from sqlalchemy import orm
try:
    from flask_login import current_user
except:
    current_user=None

class Task(db.Model):
    __tablename__ = 'tasks'

    # we do not need an ID, but ORM requires it
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    # we have two non-independent foreign keys to make query easier
    name = db.Column(db.String(200))
    resource_table = db.Column(db.String(200))

    sync_frequency = db.Column(db.Integer)
    sync_time = db.Column(db.Integer)
    incremental_sync = db.Column(db.Integer)

    sync_is_in_progress = db.Column(db.Integer)
    sync_process_id = db.Column(db.Integer)
    last_sync_record_id = db.Column(db.Integer, db.ForeignKey('sync_records.id'))
    total_records = db.Column(db.Integer)

    last_sync_record = db.relationship('SyncRecord', foreign_keys=[last_sync_record_id])

    def __repr__(self):
        return self.name

    def save(self):
        db.session.add(self)
        db.session.commit()
        return self

app/views/home.py
from flask import Blueprint,request, redirect,url_for,render_template,flash, abort, jsonify, Response
from flask_login import login_user, login_required, current_user, logout_user
from app.models import Task, SyncRecord, ErrorLog, DevUpdate
from app.utils import ts, send_confirm_mail, send_reset_password_mail, QueryDataLogHistory, QueryDataLogAnomaly, requires_auth
from flask_babel import gettext as _
from datetime import datetime
from sqlalchemy import union, or_
from sqlalchemy.sql.expression import literal_column, text
from app import db
from app import app
from flask import send_from_directory
import os
import signal
import datetime
import csv
import io

home = Blueprint('home',__name__)

@home.route('/')
@requires_auth
def index():
    all_tasks = Task.query.order_by(Task.name).all()
    running_tasks = Task.query.filter(Task.sync_is_in_progress == True).all()
    task_records = Task.query.join(SyncRecord, Task.last_sync_record_id == SyncRecord.id)
    success_tasks = task_records.filter(SyncRecord.status == 1).all()
    warning_tasks = task_records.filter(SyncRecord.status == 2).all()
    error_tasks = task_records.filter(SyncRecord.status == 3).all()
    latest_tasks = task_records.order_by(SyncRecord.begin_time.desc()).all()
    dev_updates = DevUpdate.query.order_by(DevUpdate.time.desc()).all()
    return render_template('index.html', all_tasks=all_tasks, running_tasks=running_tasks, success_tasks=success_tasks, warning_tasks=warning_tasks, error_tasks=error_tasks, latest_tasks=latest_tasks, dev_updates=dev_updates)

@home.route('/history/<int:date>')
@requires_auth
def history(date):
    if date == 0:
        title = '今日任务'
        history_records = SyncRecord.query.filter(SyncRecord.end_time >= datetime.date.today())
    elif date == 1:
        title = '昨日任务'
        history_records = SyncRecord.query.filter(SyncRecord.end_time >= datetime.date.today() - datetime.timedelta(days=1)).filter(SyncRecord.begin_time < datetime.date.today())
    elif date == 2:
        title = '历史任务'
        history_records = SyncRecord.query.filter(SyncRecord.begin_time < datetime.date.today() - datetime.timedelta(days=1))
    else:
        abort(404)
    ordered = history_records.order_by(SyncRecord.end_time.desc()).all()
    all_tasks = Task.query.order_by(Task.name).all()
    return render_template('history.html', title=title, history_records=ordered, all_tasks=all_tasks)

@home.route('/export/<int:export_type>/<string:records>')
@requires_auth
def export_records(export_type, records):
    record_ids = map(int, records.split(','))
    si = io.StringIO()
    cw = csv.writer(si)
    header = []
    if export_type == 1:
        header = ['任务名称', '数据表名', '采集周期（小时）']
    elif export_type == 2:
        header = ['任务名称', '采集批次号', '状态', '开始时间', '结束时间', '采集网页数', '采集数据总量', '新增数据量', '更新数据量', '异常数据量']
    elif export_type == 3:
        header = ['任务名称', '采集批次号', '采集时间', '数据状态', '数据表名', '数据ID', '数据内容', '数据源URL', '原始网页内容']
    elif export_type == 4:
        header = ['任务名称', '采集批次号', '采集时间', '数据表名', '数据ID', '异常类型', '异常字段名', '异常内容', '备注']
    cw.writerow(header)

    for record_id in record_ids:
        record = SyncRecord.query.filter(SyncRecord.id == record_id).first()
        if not record:
            continue
        if export_type == 1:
            cw.writerow([record.task.name, record.task.resource_table, int(record.task.sync_frequency / 3600)])
        elif export_type == 2:
            record_status_map = ['运行中', '已完成', '异常终止', '失败']
            cw.writerow([
                record.task.name, 
                record.batch_no,
                record_status_map[record.status],
                record.begin_time,
                record.end_time,
                record.crawled_webpages,
                record.total_records,
                record.new_records,
                record.updated_records,
                record.error_count
                ])
        elif export_type == 3:
            QueryDataLogHistory(cw, record.task.name, record.task.resource_table, record.batch_no)
        elif export_type == 4:
            QueryDataLogAnomaly(cw, record.task.name, record.task.resource_table, record.batch_no)

    csv_str = si.getvalue().strip('\r\n')
    time = datetime.datetime.now().strftime('%Y.%m.%d_%H.%M.%S')
    return Response(csv_str, mimetype="text/csv",
                    headers={"Content-disposition": "attachment; filename=DataLog_" + time + ".csv"})


@home.route('/task/<string:name>')
@requires_auth
def task(name):
    if not name:
   	    abort(400)
    task = Task.query.filter(Task.name == name).first()
    if not task:
   	    abort(404)
    all_tasks = Task.query.order_by(Task.name).all()
    return render_template('task.html', task=task, all_tasks=all_tasks)

@home.route('/task/<string:name>/stop')
@requires_auth
def stop_task(name):
    if not name:
   	    abort(400)
    task = Task.query.filter(Task.name == name).first()
    if not task:
   	    abort(404)
    if not task.sync_is_in_progress:
        abort(403)

    task.sync_is_in_progress = False

    try:
        os.kill(task.sync_process_id, signal.SIGKILL)
    except Exception as e:
        print(e)
    task.last_sync_record.status = 2 # error exit
    task.last_sync_record.end_time = datetime.datetime.now()
    task.save()

    return redirect(url_for('home.task', name=name))

@home.route('/task/<string:name>/start')
@requires_auth
def start_task(name):
    if not name:
   	    abort(400)
    task = Task.query.filter(Task.name == name).first()
    if not task:
   	    abort(404)
    # stop existing task before forkng new
    if task.sync_is_in_progress:
        stop_task(name)

    record = SyncRecord()
    record.task = task
    record.begin_time = datetime.datetime.now()
    record.status = 0

    record.crawled_webpages = 0
    record.total_records = 0
    record.new_records = 0
    record.updated_records = 0
    record.saved_images = 0
    record.error_count = 0

    record.save()

    import subprocess
    child_process = subprocess.Popen(["/root/scrapywrapper/RunSpider.sh", task.name])
    if not child_process:
        record.status = 3
        record.end_time = datetime.datetime.now()
        record.error_count = 1
        record.save()

        task.sync_is_in_progress = False
        task.last_sync_record = record
        task.save()

        abort(502)
        return

    task.sync_is_in_progress = True
    task.last_sync_record = record
    task.sync_process_id = child_process.pid
    task.save()
    return redirect(url_for('home.task', name=name))


@home.route('/task/<string:name>/update_status', methods=['GET', 'POST'])
@app.csrf.exempt
def task_update_sync_status(name):
    if not name:
   	    abort(400)
    task = Task.query.filter(Task.name == name).first()
    if not task:
   	    abort(404)
    record = task.last_sync_record
    if not record:
        abort(403)

    record.status = request.values.get('status')
    record.crawled_webpages = request.values.get('crawled_webpages')
    record.total_records = request.values.get('total_records')
    record.new_records = request.values.get('new_records')
    record.updated_records = request.values.get('updated_records')
    record.saved_images = request.values.get('saved_images')
    record.error_count = request.values.get('error_count')
    record.end_time = datetime.datetime.now()
    record.save()

    if int(record.status) != 0:
        task.sync_is_in_progress = False
        task.save()
    return 'OK'


@home.route('/task/<string:name>/log_error', methods=['GET', 'POST'])
@app.csrf.exempt
def task_log_error(name):
    if not name:
   	    abort(400)
    task = Task.query.filter(Task.name == name).first()
    if not task:
   	    abort(404)

    # TODO

    return redirect(url_for('home.task', name=name))

@home.route('/static/<path:path>')
def send_static(path):
    return send_from_directory('static', path)

@home.route('/task/new', methods=['POST'])
@app.csrf.exempt
@requires_auth
def new_task():
    name = request.values.get('name')
    sync_frequency = request.values.get('freq')
    sync_time = request.values.get('time')
    incremental = request.values.get('incremental')
    try:
        sync_time = int(sync_time)
    except:
        ts = sync_time.split(":")
        sync_time = 0
        for t in range(0,3):
            try:
                sync_time *= 60
                sync_time += int(ts[t])
            except:
                pass

    incremental = 1 if incremental else 0

    task = Task.query.filter(Task.name == name).first()
    if not task:
        task = Task()
    task.name = name
    task.sync_frequency = sync_frequency
    task.sync_time = sync_time
    task.incremental_sync = incremental
    task.save()
    return redirect(url_for('home.task', name=name))

@home.route('/dev_update/new', methods=['POST'])
@app.csrf.exempt
@requires_auth
def new_dev_update():
    task_name = request.values.get('task')
    task = Task.query.filter(Task.name == task_name).first()
    if not task:
        abort(404)
    update = DevUpdate()
    update.task = task
    update.title = request.values.get('title')
    update.time = datetime.datetime.now()
    update.content = request.values.get('content')
    update.save()
    return redirect(url_for('home.index'))

app/templates/common-footer.html
    <!-- jQuery -->
    <script src="/static/vendor/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="/static/vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="/static/vendor/metisMenu/metisMenu.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="/static/dist/js/sb-admin-2.js"></script>

</body>

</html>

app/templates/common-header.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>数据采集后台管理系统</title>

    <!-- Bootstrap Core CSS -->
    <link href="/static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="/static/vendor/metisMenu/metisMenu.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/static/dist/css/sb-admin-2.css" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="/static/vendor/morrisjs/morris.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="/static/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

{% include 'navbar.html' %}

app/templates/history.html
{% include 'common-header.html' %}

        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">{{ title }}</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <i class="fa fa-clock-o fa-fw"></i> 导出选中任务 CSV
                        </div>
                        <div class="panel-body">
                <button type="submit" class="btn btn-primary" onclick="ExportTask(1)">导出采集配置</button>
                <button type="submit" class="btn btn-primary" onclick="ExportTask(2)">导出采集统计</button>
                <button type="submit" class="btn btn-primary" onclick="ExportTask(3)">导出采集日志</button>
                <button type="submit" class="btn btn-primary" onclick="ExportTask(3)">导出异常日志</button>
                        </div>
                    </div>

                            <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                                <thead>
                                    <tr>
                                        <th>
                                            <input type="checkbox" id="csv-selectall" onclick="SelectAll()">
                                        </th>
                                        <th>任务名称</th>
                                        <th>采集批次号</th>
										<th>状态</th>
                                        <th>开始时间</th>
                                        <th>结束时间</th>
                                        <th>采集网页数</th>
										<th>采集数据总量</th>
                                        <th>新增数据量</th>
                                        <th>更新数据量</th>
										<th>异常数据量</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for record in history_records %}
                                    <tr class="
                                    {% if record.status == 0 %}info{% endif %}
                                    {% if record.status == 1 %}success{% endif %}
                                    {% if record.status == 2 %}warning{% endif %}
                                    {% if record.status == 3 %}danger{% endif %}
                                    ">
                                        <td>
                                            <input type="checkbox" class="csv-checkbox" id="csv-checkbox-{{ record.id }}" name="{{ record.id }}">
                                        </td>
                                        <td>{{ record.task.name }}</td>
                                        <td>{{ record.batch_no }}</td>
										<td>
                                    {% if record.status == 0 %}运行中{% endif %}
                                    {% if record.status == 1 %}成功{% endif %}
                                    {% if record.status == 2 %}异常终止{% endif %}
                                    {% if record.status == 3 %}失败{% endif %}
                                        </td>
                                        <td>{{ record.begin_time|localtime }}</td>
                                        <td>{{ record.end_time|localtime }}</td>
                                        <td>{{ record.crawled_webpages }}</td>
                                        <td>{{ record.total_records }}</td>
                                        <td>{{ record.new_records }}</td>
                                        <td>{{ record.updated_records }}</td>
                                        <td>{{ record.error_count }}</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
 
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

<iframe id="csv_download_iframe" style="display:none;"></iframe>
<script>
function ExportTask(type) {
    var selected = [];
    $("input:checkbox[class=csv-checkbox]:checked").each(function(){
        selected.push($(this).prop('name'));
    });
    if (selected.length == 0) {
        alert('请选择至少一条记录！');
        return;
    }
    $('#csv_download_iframe').attr({
        'src': "/export" + "/" + type + "/" + selected.join(",")
    });
}

function SelectAll() {
    if ($('#csv-selectall').prop('checked')) {
        $('.csv-checkbox').prop('checked', true);
    } else {
        $('.csv-checkbox').prop('checked', false);
    }
}
</script>

{% include 'common-footer.html' %}

app/templates/navbar.html
<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">数据采集后台管理系统</a>
            </div>
            <!-- /.navbar-header -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Search (TODO)">
                                <span class="input-group-btn">
                                <button class="btn btn-default" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                            </div>
                            <!-- /input-group -->
                        </li>
                        <li>
                            <a href="/"><i class="fa fa-dashboard fa-fw"></i> 任务总览</a>
                        </li>
                        <li>
                            <a href="{{ url_for('home.history', date=0) }}"><i class="fa fa-dashboard fa-fw"></i> 今日任务</a>
                        </li>
                        <li>
                            <a href="{{ url_for('home.history', date=1) }}"><i class="fa fa-dashboard fa-fw"></i> 昨日任务</a>
                        </li>
                        <li>
                            <a href="{{ url_for('home.history', date=2) }}"><i class="fa fa-dashboard fa-fw"></i> 历史任务</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> 采集任务配置<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                            {% for task in all_tasks %}
                                <li><a href="{{ url_for('home.task', name=task.name) }}">{{ task.name }}</a></li>
                            {% endfor %}
                            </ul>
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

app/templates/task.html
{% include 'common-header.html' %}

        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">{{ task.name }}</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-comments fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">{{ task.last_sync_record.total_records }}</div>
                                    <div>条记录</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                                <span class="pull-left">查看详情</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-green">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-tasks fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">{{ task.last_sync_record.new_records }}</div>
                                    <div>条新增记录</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                                <span class="pull-left">查看详情</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-yellow">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-shopping-cart fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">{{ task.last_sync_record.updated_records }}</div>
                                    <div>条更新记录</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                                <span class="pull-left">查看详情</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-red">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-support fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">{{ task.last_sync_record.error_count }}</div>
                                    <div>项错误信息</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                                <span class="pull-left">查看详情</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
            <!-- /.row -->
            <div class="row">
               <div class="col-lg-2">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <i class="fa fa-clock-o fa-fw"></i> 更新配置
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                                    <form role="form" method="post" action="{{ url_for('home.new_task') }}">
                                        <input type="hidden" name="name" value="{{ task.name }}" />
                                        <div class="form-group">
                                            <label>更新周期</label>
                                            <select name="freq" class="form-control">
                                                <option value="3600" {% if task.sync_frequency == 3600 %}selected="selected"{% endif %}>每小时</option>
                                                <option value="86400" {% if task.sync_frequency == 86400 %}selected="selected"{% endif %}>每天</option>
                                                <option value="604800" {% if task.sync_frequency == 604800 %}selected="selected"{% endif %}>每周</option>
                                                <option value="2592000" {% if task.sync_frequency == 2592000 %}selected="selected"{% endif %}>每月</option>
                                                <option value="31536000" {% if task.sync_frequency == 31536000 %}selected="selected"{% endif %}>每年</option>
                                            </select>
                                        </div>
                                        <div class="form-group">
                                            <label>具体更新时间</label>
                                            <input name="time" class="form-control" placeholder="例如 9:00" value="{{ task.sync_time|time_interval }}">
                                        </div>
                                        <div class="form-group">
                                            <label>是否增量更新</label>
                                            <label class="checkbox-inline">
                                                <input type="checkbox" name="incremental" {% if task.incremental_sync %}checked="checked"{% endif %}>&nbsp;
                                            </label>
                                        </div>
                                        <button type="submit" class="btn btn-default">更新采集配置</button>
                                    </form>
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->

                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <i class="fa fa-clock-o fa-fw"></i> 更新操作
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            {% if task.sync_is_in_progress %}
							<a href="{{ url_for('home.stop_task', name=task.name) }}"><button type="button" class="btn btn-danger btn-lg btn-block">停止正在运行的更新</button></a>
                            {% else %}
							<a href="{{ url_for('home.start_task', name=task.name) }}"><button type="button" class="btn btn-danger btn-lg btn-block">立即开始更新</button></a>
                            {% endif %}
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
 
                </div>
                <!-- /.col-lg-4 -->
                <div class="col-lg-10">
                    <!-- /.panel -->
                    <div class="panel panel-default">
                        <div class="panel-heading">

                            <i class="fa fa-clock-o fa-fw"></i> 采集记录
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                                <thead>
                                    <tr>
                                        <th>采集批次号</th>
										<th>状态</th>
                                        <th>开始时间</th>
                                        <th>结束时间</th>
                                        <th>采集网页数</th>
										<th>采集数据总量</th>
                                        <th>新增数据量</th>
                                        <th>更新数据量</th>
										<th>异常数据量</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for record in task.sync_records %}
                                    <tr class="
                                    {% if record.status == 0 %}info{% endif %}
                                    {% if record.status == 1 %}success{% endif %}
                                    {% if record.status == 2 %}warning{% endif %}
                                    {% if record.status == 3 %}danger{% endif %}
                                    ">
                                        <td>{{ record.batch_no }}</td>
										<td>
                                    {% if record.status == 0 %}运行中{% endif %}
                                    {% if record.status == 1 %}成功{% endif %}
                                    {% if record.status == 2 %}异常终止{% endif %}
                                    {% if record.status == 3 %}失败{% endif %}
                                        </td>
                                        <td>{{ record.begin_time|localtime }}</td>
                                        <td>{{ record.end_time|localtime }}</td>
                                        <td>{{ record.crawled_webpages }}</td>
                                        <td>{{ record.total_records }}</td>
                                        <td>{{ record.new_records }}</td>
                                        <td>{{ record.updated_records }}</td>
                                        <td>{{ record.error_count }}</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
						</div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-8 -->
 
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

{% include 'common-footer.html' %}